//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Index</summary>
	[PublishedContentModel("index")]
	public partial class Index : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "index";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Index(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Index, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// footerText
		///</summary>
		[ImplementPropertyType("footerText")]
		public IHtmlString FooterText
		{
			get { return this.GetPropertyValue<IHtmlString>("footerText"); }
		}

		///<summary>
		/// Header
		///</summary>
		[ImplementPropertyType("header")]
		public IHtmlString Header
		{
			get { return this.GetPropertyValue<IHtmlString>("header"); }
		}

		///<summary>
		/// Info: Information about grid
		///</summary>
		[ImplementPropertyType("info")]
		public Newtonsoft.Json.Linq.JToken Info
		{
			get { return this.GetPropertyValue<Newtonsoft.Json.Linq.JToken>("info"); }
		}

		///<summary>
		/// menu list: menu bar items
		///</summary>
		[ImplementPropertyType("menuList")]
		public object MenuList
		{
			get { return this.GetPropertyValue("menuList"); }
		}

		///<summary>
		/// webisteName: Name of the website to be disaplay
		///</summary>
		[ImplementPropertyType("webisteName")]
		public string WebisteName
		{
			get { return this.GetPropertyValue<string>("webisteName"); }
		}
	}
}
