//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>News Overview</summary>
	[PublishedContentModel("newsOverview")]
	public partial class NewsOverview : PublishedContentModel, INews
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "newsOverview";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public NewsOverview(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<NewsOverview, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// NewsBodyText: News
		///</summary>
		[ImplementPropertyType("newsBodyText")]
		public IHtmlString NewsBodyText
		{
			get { return this.GetPropertyValue<IHtmlString>("newsBodyText"); }
		}

		///<summary>
		/// NewsTitle: News heading
		///</summary>
		[ImplementPropertyType("newsTitle")]
		public IHtmlString NewsTitle
		{
			get { return Umbraco.Web.PublishedContentModels.News.GetNewsTitle(this); }
		}
	}
}
