//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UmbracoHelios
{
    using System;
    using System.Collections.Generic;
    
    public partial class umbracoUserGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public umbracoUserGroup()
        {
            this.umbracoUserGroup2App = new HashSet<umbracoUserGroup2App>();
            this.umbracoUserGroup2NodePermission = new HashSet<umbracoUserGroup2NodePermission>();
            this.umbracoUsers = new HashSet<umbracoUser>();
        }
    
        public int id { get; set; }
        public string userGroupAlias { get; set; }
        public string userGroupName { get; set; }
        public string userGroupDefaultPermissions { get; set; }
        public System.DateTime createDate { get; set; }
        public System.DateTime updateDate { get; set; }
        public string icon { get; set; }
        public Nullable<int> startContentId { get; set; }
        public Nullable<int> startMediaId { get; set; }
    
        public virtual umbracoNode umbracoNode { get; set; }
        public virtual umbracoNode umbracoNode1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<umbracoUserGroup2App> umbracoUserGroup2App { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<umbracoUserGroup2NodePermission> umbracoUserGroup2NodePermission { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<umbracoUser> umbracoUsers { get; set; }
    }
}
