//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UmbracoHelios
{
    using System;
    using System.Collections.Generic;
    
    public partial class umbracoUserGroup2NodePermission
    {
        public int userGroupId { get; set; }
        public int nodeId { get; set; }
        public string permission { get; set; }
    
        public virtual umbracoNode umbracoNode { get; set; }
        public virtual umbracoUserGroup umbracoUserGroup { get; set; }
    }
}
