//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UmbracoHelios
{
    using System;
    using System.Collections.Generic;
    
    public partial class umbracoUserGroup2App
    {
        public int userGroupId { get; set; }
        public string app { get; set; }
    
        public virtual umbracoUserGroup umbracoUserGroup { get; set; }
    }
}
